# Generated by Django 4.2 on 2026-04-13 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('PRESIDENT', 'President'), ('VP', 'Vice President'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural Captain')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science')], max_length=10, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year')], max_length=5, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, choices=[('PRESIDENT', 'President'), ('VP', 'Vice President'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural Captain')], null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.candidate')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.role')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.student')),
            ],
            options={
                'unique_together': {('student', 'role')},
            },
        ),
    ]
