# Generated by Django 4.2 on 2026-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_alter_vote_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionstatus',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
