# Generated by Django 4.2 on 2026-04-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_electionstatus_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='votes_cast',
            field=models.IntegerField(default=0),
        ),
    ]
