# Generated by Django 4.2 on 2026-04-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_student_votes_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.student'),
        ),
    ]
