# Generated by Django 4.2 on 2026-04-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0005_candidate_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='votes',
        ),
    ]
